"""
FFP Smart MVP — Pillar 3: Pricing & Business Model
===================================================
Weight: 20% of composite score (Pre-Seed)

Scoring philosophy: NEUTRAL for all pre-revenue states.
No penalty for absence of paying customers at Pre-Seed.

Pricing Clarity Rules:
  Clear         → model_type ✓ + target_customer ✓ + pricing_metric ✓ → 65
  SomewhatClear → model_type ✓ + target_customer ✓, pricing_metric ✗ → 50
                  OR Enterprise + 'contact sales'                      → 50
  Unclear       → model_type ✗ OR target_customer ✗                   → 35
  PreRevenue    → revenue = 0 → score forced to 50 in composite

Gemini 2.0 Flash (free tier, Google Search grounding) generates a 2–3 sentence
pricing summary with live 2026 market benchmarks.
"""

import json
import os
import requests
from typing import Optional


# ──────────────────────────────────────────────
# Valid pricing model types (enum guard)
# ──────────────────────────────────────────────
VALID_PRICING_MODELS = {
    "Free", "Freemium", "Subscription", "Usage-Based",
    "Transaction Fee", "Enterprise", "Other",
}

DATA_PROVENANCE_NOTE = (
    "Pricing model: founder-submitted. "
    "AI summary generated by Gemini 2.0 Flash with Google Search grounding (2026 benchmarks)."
)

GEMINI_URL = (
    "https://generativelanguage.googleapis.com/v1beta"
    "/models/gemini-2.0-flash:generateContent"
)


# ──────────────────────────────────────────────
# Gemini Pricing Summary
# ──────────────────────────────────────────────
def _generate_gemini_pricing_summary(
    pricing_model_type: str,
    target_customer: str,
    pricing_metric: str,
    price_range: str,
    market_type: str,
    geographic_focus: str,
    gemini_api_key: str,
) -> str:
    """
    Call Gemini 2.0 Flash with Google Search grounding to produce a 2–3 sentence
    pricing summary with live 2026 market benchmarks.
    Returns empty string on any failure — does NOT block scoring.
    """
    if not gemini_api_key:
        return ""

    system_instruction = (
        "You are a senior VC investment analyst reviewing a startup's pricing model. "
        "Use Google Search to find the current 2026 industry benchmarks (typical price ranges, "
        "gross margins, LTV:CAC ratios) for the founder's specific market and pricing model type. "
        "Write a 2–3 sentence factual summary of the pricing model and how it compares to current "
        "benchmarks. If no relevant benchmarks are found, write the summary without benchmark "
        "comparisons. Be concise and direct. No preamble."
    )
    user_message = (
        f"Pricing model: {pricing_model_type}. "
        f"Target customer: {target_customer}. "
        f"Pricing metric: {pricing_metric or 'not specified'}. "
        f"Price range: {price_range or 'not specified'}. "
        f"Market: {market_type}, {geographic_focus}."
    )
    payload = {
        "system_instruction": {"parts": [{"text": system_instruction}]},
        "contents": [{"parts": [{"text": user_message}]}],
        "generationConfig": {"temperature": 0.0, "maxOutputTokens": 300},
        # Google Search grounding tool
        "tools": [{"google_search": {}}],
    }
    try:
        resp = requests.post(
            f"{GEMINI_URL}?key={gemini_api_key}",
            headers={"Content-Type": "application/json"},
            json=payload,
            timeout=20,
        )
        resp.raise_for_status()
        return (
            resp.json()
            .get("candidates", [{}])[0]
            .get("content", {})
            .get("parts", [{}])[0]
            .get("text", "")
            .strip()
        )
    except Exception:
        return ""


# ──────────────────────────────────────────────
# Pricing Clarity Rules
# ──────────────────────────────────────────────
def _compute_pricing_clarity(
    pricing_model_type: Optional[str],
    target_customer: Optional[str],
    pricing_metric: Optional[str],
    price_range: Optional[str],
    revenue: float,
) -> tuple[str, int]:
    """
    Returns (pricing_clarity_label, pillar_score).
    PreRevenue always returns score=50 (forced at composite level also).
    """
    is_pre_revenue = revenue == 0

    has_model = bool(pricing_model_type)
    has_customer = bool(target_customer)
    has_metric = bool(pricing_metric)

    if has_model and has_customer and has_metric:
        label, score = "Clear", 65
    elif has_model and has_customer:
        # Check Enterprise + contact sales case
        label, score = "SomewhatClear", 50
    elif not has_model or not has_customer:
        label, score = "Unclear", 35
    else:
        label, score = "SomewhatClear", 50

    if is_pre_revenue:
        return "PreRevenue", 50

    return label, score


# ──────────────────────────────────────────────
# Main Entry Point
# ──────────────────────────────────────────────
def score_pricing_pipeline(
    pricing_model_type: Optional[str],
    target_customer: Optional[str],
    pricing_metric: Optional[str] = None,
    price_range: Optional[str] = None,
    who_pays_vs_who_uses: Optional[str] = None,
    paying_segment: Optional[str] = None,   # stored only — NOT scored at Pre-Seed
    evidence_links: Optional[list[str]] = None,
    analyst_notes: Optional[str] = None,
    revenue_curr_period: float = 0.0,
    market_type: str = "",
    geographic_focus: str = "",
    gemini_api_key: str = "",
) -> dict:
    """
    Compute the Pricing & Business Model pillar score.

    paying_segment is stored for Seed-stage re-evaluation but does NOT
    affect the Pre-Seed pillar score.

    Returns
    -------
    dict with pricing_clarity_label, pricing_pillar_score, gemini_pricing_summary,
    evidence_links, analyst_notes, paying_segment (stored), data_provenance_note.
    """
    evidence_links = evidence_links or []

    pricing_clarity_label, pillar_score = _compute_pricing_clarity(
        pricing_model_type=pricing_model_type,
        target_customer=target_customer,
        pricing_metric=pricing_metric,
        price_range=price_range,
        revenue=revenue_curr_period,
    )

    # Gemini summary — non-blocking
    gemini_pricing_summary = ""
    if pricing_model_type and target_customer:
        gemini_pricing_summary = _generate_gemini_pricing_summary(
            pricing_model_type=pricing_model_type,
            target_customer=target_customer,
            pricing_metric=pricing_metric or "",
            price_range=price_range or "",
            market_type=market_type,
            geographic_focus=geographic_focus,
            gemini_api_key=gemini_api_key,
        )

    return {
        "pricing_clarity_label": pricing_clarity_label,
        "pricing_pillar_score": pillar_score,
        "gemini_pricing_summary": gemini_pricing_summary,
        "pricing_model_type": pricing_model_type,
        "target_customer": target_customer,
        "pricing_metric": pricing_metric,
        "price_range": price_range,
        "who_pays_vs_who_uses": who_pays_vs_who_uses,
        "paying_segment": paying_segment,           # stored, NOT scored at Pre-Seed
        "evidence_links": evidence_links,
        "analyst_notes": analyst_notes,
        "data_provenance_note": DATA_PROVENANCE_NOTE,
    }